"""initial schema

Revision ID: a614969347a7
Revises: 
Create Date: 2026-08-29 14:32:59.786210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a614969347a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frequency', sa.Interval(), nullable=False),
    sa.Column('state', sa.Enum('Unknown', 'Critical', 'Fair', 'Good', name='inspectionstate'), nullable=False),
    sa.Column('last_performed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_inspected', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_room_id'), 'tasks', ['room_id'], unique=False)
    op.create_table('random_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_random_tasks_id'), 'random_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_random_tasks_number'), 'random_tasks', ['number'], unique=True)
    op.create_index(op.f('ix_random_tasks_task_id'), 'random_tasks', ['task_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_task_id'), 'scheduled_tasks', ['task_id'], unique=True)
    op.create_table('task_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_notes_id'), 'task_notes', ['id'], unique=False)
    op.create_index(op.f('ix_task_notes_task_id'), 'task_notes', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_notes_task_id'), table_name='task_notes')
    op.drop_index(op.f('ix_task_notes_id'), table_name='task_notes')
    op.drop_table('task_notes')
    op.drop_index(op.f('ix_scheduled_tasks_task_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_random_tasks_task_id'), table_name='random_tasks')
    op.drop_index(op.f('ix_random_tasks_number'), table_name='random_tasks')
    op.drop_index(op.f('ix_random_tasks_id'), table_name='random_tasks')
    op.drop_table('random_tasks')
    op.drop_index(op.f('ix_tasks_room_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
